[phases.setup]
nixPkgs = ["nginx", "php"]

[phases.build]
cmds = [
    "mkdir -p /etc/nginx/conf.d",
    "echo 'server {' > /etc/nginx/conf.d/default.conf",
    "echo '    listen 3000;' >> /etc/nginx/conf.d/default.conf",
    "echo '    server_name localhost;' >> /etc/nginx/conf.d/default.conf",
    "echo '    root /app;' >> /etc/nginx/conf.d/default.conf",
    "echo '    index index.php;' >> /etc/nginx/conf.d/default.conf",
    "echo '    server_tokens off;' >> /etc/nginx/conf.d/default.conf",
    "echo '    gzip on;' >> /etc/nginx/conf.d/default.conf",
    "echo '    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;' >> /etc/nginx/conf.d/default.conf",
    "echo '    rewrite ^/aboutUs$ /aboutUs.php last;' >> /etc/nginx/conf.d/default.conf",
    "echo '    rewrite ^/professions$ /professions.php last;' >> /etc/nginx/conf.d/default.conf",
    "echo '    rewrite ^/references$ /references.php last;' >> /etc/nginx/conf.d/default.conf",
    "echo '    rewrite ^/clients$ /clients.php last;' >> /etc/nginx/conf.d/default.conf",
    "echo '    rewrite ^/contact$ /contact.php last;' >> /etc/nginx/conf.d/default.conf",
    "echo '    rewrite ^/reference/([0-9]+)$ /reference.php?id=$1 last;' >> /etc/nginx/conf.d/default.conf",
    "echo '    location / {' >> /etc/nginx/conf.d/default.conf",
    "echo '        try_files $uri $uri/ /index.php?$query_string;' >> /etc/nginx/conf.d/default.conf",
    "echo '    }' >> /etc/nginx/conf.d/default.conf",
    "echo '    location ~ \\.php$ {' >> /etc/nginx/conf.d/default.conf",
    "echo '        fastcgi_pass 127.0.0.1:9000;' >> /etc/nginx/conf.d/default.conf",
    "echo '        fastcgi_index index.php;' >> /etc/nginx/conf.d/default.conf",
    "echo '        include fastcgi_params;' >> /etc/nginx/conf.d/default.conf",
    "echo '        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> /etc/nginx/conf.d/default.conf",
    "echo '    }' >> /etc/nginx/conf.d/default.conf",
    "echo '    location ~* \\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {' >> /etc/nginx/conf.d/default.conf",
    "echo '        expires max;' >> /etc/nginx/conf.d/default.conf",
    "echo '        access_log off;' >> /etc/nginx/conf.d/default.conf",
    "echo '    }' >> /etc/nginx/conf.d/default.conf",
    "echo '}' >> /etc/nginx/conf.d/default.conf"
]

[start]
cmd = "service nginx start && php-fpm"